config/routes.rb
Rails.application.routes.draw do
  root "exercises#index"

  resources :exercises
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }

  has_many :links
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      redirect_to @exercise
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def exercise_params
    params.require(:exercise).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<div data-controller="search">
  <input type="text" name="search" id="search" data-search-target="query">
  <button type="submit" data-action="search#runSearch">Search</button>

  <ul>
    <% @exercises.each do |exercise| %>
      <li data-search-target="exercise">
        <%= link_to exercise.title, exercise %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New Exercise", new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= form_with model: @exercise do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @exercise.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/show.html.erb
<h1><%= @exercise.title %></h1>

<ul>
  <li><%= link_to "Back to all exercises", exercises_path %></li>
  <li>
    <%= link_to "Delete", exercise_path(@exercise), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness DB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>